### ISSUE TITLE
怎么能弃坑呢，更新一下呗

### ISSUE THREAD

**Issue by wallfacertony** [Him188/MoneyShop#1]
个人认为这个插件是不错的，能自定名称，简洁，明了。
star了
毕竟我的服务器主要经济插件就是你的Money....
 好歹跟money v2.2.0做个适配呗。。。
16:40:56 [CRITICAL] "ÎÞ·¨´¦ÀíÊÂ¼þ 'cn.nukkit.event.player.PlayerInteractEvent' ÖÁ 'MoneyShop v1.0.0'£ºnull ÓÚ money.MoneyShop"
16:40:56 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:542)
        at cn.nukkit.level.Level.useItemOn(Level.java:1994)
        at cn.nukkit.level.Level.useItemOn(Level.java:1961)
        at cn.nukkit.Player.handleDataPacket(Player.java:2884)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.nukkit.network.Network.processPackets(Network.java:179)
        at cn.nukkit.network.Network.processBatch(Network.java:161)
        at cn.nukkit.Player.handleDataPacket(Player.java:2042)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1076)
        at cn.nukkit.Server.tickProcessor(Server.java:853)
        at cn.nukkit.Server.start(Server.java:830)
        at cn.nukkit.Server.<init>(Server.java:513)
        at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.NoSuchMethodError: cn.nukkit.blockentity.BlockEntitySign.setText(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
        at money.MoneyShop.updateSign(MoneyShop.java:615)
        at money.MoneyShop.onTouch(MoneyShop.java:96)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 18 more

顺便推广一下服务器：
pe1.8
IP：mcpe.wallfacer.tk
port： 19132

以上

**Comment by Him188** [comment]
好的，现在还有人用是让我很欣慰的....已列入TODO，可能需要过一周时间我才能有空做这个

**Comment by wallfacertony** [comment]
太感谢了（*＾ワ＾*）

(=・怒赞ω・=)

**Comment by Him188** [comment]
咕咕咕...可能要再等一会

**Comment by wallfacertony** [comment]
=_=……

嘛，除夕快乐ヾ(❀╹◡╹)ﾉ~

**Comment by Him188** [comment]
新年快乐, 我先做适配吧, 重写是不可能了的 我觉得

**Comment by Him188** [comment]
ok了, 用新的API编译了.

不过这个插件好旧了, 不考虑下用 GUIShop 嘛? ヾ(❀╹◡╹)ﾉ~

**Comment by wallfacertony** [comment]
再次感谢(๑`･ᴗ･´๑)

GUIShop那个之前用过，当时回收系统好像有点bug，可能是因为当时用的老版money。

我再去试试 ^_^
